apiVersion: v1
kind: Pod
metadata:
  name: etcdutl
  namespace: openshift-etcd
spec:
  volumes:
    - name: "etcd-data"
      hostPath:
        path: /var/lib/etcd
  containers:
    - image: gcr.io/etcd-development/etcd:v3.5.9
      name: etcdutl
      # Run as root to access the hostPath volume
      securityContext:
        runAsUser: 0
      command:
        - etcdutl
        - snapshot
        - status
        - /var/lib/etcd/etcd-snapshot.db
      volumeMounts:
        - mountPath: /var/lib/etcd
          name: "etcd-data"
