#!/bin/bash
# Airgapped deployment — Approach A variant: declarative mirroring via `oc mirror` v2.
# Advantage over skopeo + hand-written ImageTagMirrorSet: one ImageSetConfiguration
# mirrors nginx + alpine in a single pass, AND oc-mirror generates the
# ImageTagMirrorSet for you from what it actually mirrored. Pulled layers are
# cached in ~/.oc-mirror/.cache, so rerunning (e.g. after adding more images to
# the ImageSetConfiguration) doesn't re-download unchanged layers from docker.io.
# Requires oc-mirror v2 (the `--v2` flag is mandatory on OCP 4.21 clients).
# Run prereqs-registry.sh first (local registry + insecureRegistries patch).

set -euxo pipefail

DIR=$(cd "$(dirname "$0")"; pwd -P)

. $DIR/../conf.version.sh

ID="$(whoami)"
NS="airgapped-$ID"
RELEASE="nginx"
# IP de l'hôte sur le bridge libvirt (virbr0), accessible depuis la VM CRC
HOST_IP=$(ip -4 addr show virbr0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1)
LOCAL_REGISTRY="${HOST_IP}:5000"
MIRROR_WORKSPACE="/tmp/oc-mirror-workspace"

ink "Mirror nginx + alpine in one pass via oc-mirror v2 (declarative ImageSetConfiguration)"
mkdir -p "$MIRROR_WORKSPACE"
export NGINX_VERSION ALPINE_VERSION
envsubst < "$DIR/manifests/imageset-config.yaml" > /tmp/imageset-config.yaml
oc mirror -c /tmp/imageset-config.yaml \
    --workspace "file://$MIRROR_WORKSPACE" \
    --dest-tls-verify=false \
    "docker://$LOCAL_REGISTRY" \
    --v2

ink "Apply the ImageTagMirrorSet generated by oc-mirror itself — no manual YAML to maintain"
ITMS="$MIRROR_WORKSPACE/working-dir/cluster-resources/itms-oc-mirror.yaml"
cat "$ITMS"
kubectl apply -f "$ITMS"

ink "Wait for the new mirror rule to land in /etc/containers/registries.conf on the worker node"
WORKER=$(oc get nodes -l node-role.kubernetes.io/worker -o jsonpath='{.items[0].metadata.name}')
until oc debug node/$WORKER -- chroot /host cat /etc/containers/registries.conf | grep -q "docker.io/library"; do
    sleep 5
done

kubectl delete ns -l "airgapped=$ID" --ignore-not-found
oc new-project "$NS"
kubectl label ns "$NS" "airgapped=$ID"
kubectl config set-context --current --namespace="$NS"

ink "Install local nginx chart with mirror=true (nginx + alpine sidecar, both pulled from mirror)"
helm install "$RELEASE" "$DIR/../nginx-chart" \
    --namespace "$NS" \
    --values "$DIR/../6_helm_migration/manifests/nginx-values-v2.yaml" \
    --set image.pullPolicy=Always \
    --set sidecar.image.pullPolicy=Always \
    --set mirror=true \
    --set sidecar.image.tag="$ALPINE_VERSION" \
    --wait --timeout 120s

ink "Verify both containers are running"
kubectl get pod -l "app=$RELEASE" -o jsonpath='{range .items[0].spec.containers[*]}{.name}: {.image}{"\n"}{end}'
kubectl describe pod -l "app=$RELEASE" | grep -A10 "Events:"

ink "Verify both images were pulled from local registry"
podman logs local-registry 2>&1 | grep GET
