
[openshift@openshift ~]$ kubectl apply -f machine-aws.yaml
Error from server (Forbidden): error when creating "machine-aws.yaml": admission webhook "default.machine.machine.openshift.io" denied the request: providerSpec.value: Invalid value: v1beta1.AzureMachineProviderSpec{TypeMeta:v1.TypeMeta{Kind:"AWSMachineProviderConfig", APIVersion:"awsproviderconfig.openshift.io/v1beta1"}, ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry(nil)}, UserDataSecret:(*v1.SecretReference)(0xc000663020), CredentialsSecret:(*v1.SecretReference)(0xc000663040), Location:"", VMSize:"", Image:v1beta1.Image{Publisher:"", Offer:"", SKU:"", Version:"", ResourceID:"", Type:""}, OSDisk:v1beta1.OSDisk{OSType:"", ManagedDisk:v1beta1.OSDiskManagedDiskParameters{StorageAccountType:"", DiskEncryptionSet:(*v1beta1.DiskEncryptionSetParameters)(nil), SecurityProfile:v1beta1.VMDiskSecurityProfile{DiskEncryptionSet:v1beta1.DiskEncryptionSetParameters{ID:""}, SecurityEncryptionType:""}}, DiskSizeGB:0, DiskSettings:v1beta1.DiskSettings{EphemeralStorageLocation:""}, CachingType:""}, DataDisks:[]v1beta1.DataDisk(nil), SSHPublicKey:"", PublicIP:false, Tags:map[string]string(nil), SecurityGroup:"", ApplicationSecurityGroups:[]string(nil), Subnet:"", PublicLoadBalancer:"", InternalLoadBalancer:"", NatRule:(*int64)(nil), ManagedIdentity:"", Vnet:"", Zone:(*string)(nil), NetworkResourceGroup:"", ResourceGroup:"", SpotVMOptions:(*v1beta1.SpotVMOptions)(nil), SecurityProfile:(*v1beta1.SecurityProfile)(nil), UltraSSDCapability:"", AcceleratedNetworking:false, AvailabilitySet:"", Diagnostics:v1beta1.AzureDiagnostics{Boot:(*v1beta1.AzureBootDiagnostics)(nil)}}: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field AzureMachineProviderSpec.subnet of type string

[openshift@openshift ~]$ kubectl logs  -n openshift-machine-api machine-api-controllers-58d8d5b789-w8zcq   | tail -n 3
Defaulted container "machineset-controller" out of: machineset-controller, machine-controller, nodelink-controller, machine-healthcheck-controller, kube-rbac-proxy-machineset-mtrc, kube-rbac-proxy-machine-mtrc, kube-rbac-proxy-mhc-mtrc
I1122 21:11:09.581334       1 machine_webhook.go:796] Defaulting Azure providerSpec
## I1122 21:11:40.694221       1 machine_webhook.go:528] Mutate webhook called for Machine: aws-school2
I1122 21:11:40.694244       1 machine_webhook.go:796] Defaulting Azure providerSpec
