apiVersion: v1
kind: Pod
metadata:
  name: conflicting-pod
spec:
  containers:
    - name: my-container
      image: nginx
  nodeSelector:
    disktype: ssd  # Requires "disktype: ssd"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: disktype
                operator: In
                values:
                  - hdd  # Requires "disktype: hdd"
