apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: demo-z2jlq
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
  name: demo-z2jlq-worker-francecentral4
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: demo-z2jlq
      machine.openshift.io/cluster-api-machineset: demo-z2jlq-worker-francecentral4
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: demo-z2jlq
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: demo-z2jlq-worker-francecentral4
    spec:
      metadata:
        labels:
          machine.openshift.io/cluster-api-machineset: demo-z2jlq-worker-francecentral4
          node-role.kubernetes.io/worker: ""
      providerSpec:
        value:
          apiVersion: azureproviderconfig.openshift.io/v1beta1
          credentialsSecret:
            name: azure-cloud-credentials
            namespace: openshift-machine-api
          image:
            offer: ""
            publisher: ""
            resourceID: /resourceGroups/demo-z2jlq-rg/providers/Microsoft.Compute/galleries/gallery_demo_z2jlq/images/demo-z2jlq-gen2/versions/latest
            sku: ""
            version: ""
          internalLoadBalancer: ""
          kind: AzureMachineProviderSpec
          location: francecentral
          managedIdentity: demo-z2jlq-identity
          metadata:
          natRule: null
          networkResourceGroup: ""
          osDisk:
            diskSizeGB: 128
            managedDisk:
              storageAccountType: Premium_LRS
            osType: Linux
          publicIP: false
          publicLoadBalancer: ""
          resourceGroup: demo-z2jlq-rg
          sshPrivateKey: ""
          sshPublicKey: ""
          subnet: demo-z2jlq-worker-subnet
          userDataSecret:
            name: worker-user-data
          vmSize: Standard_D4s_v3
          vnet: demo-z2jlq-vnet
          zone: "1"
